<?php

namespace AppBundle\Entity\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAwaitingManualPassportReview()
    {
        return $this->_em->getRepository('AppBundle:Customer')
            ->createQueryBuilder('c')
            ->andWhere('c.marking LIKE :awaitingManualReview')
            ->setParameter('awaitingManualReview', '%manual_passport_review%') //eurghh
            ->getQuery()
        ;
    }
}
